import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import Header from "./components/Header";
import PostCreateCard from "./components/PostCreateCard";
import BlueitPremium from "./components/BlueitPremium";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-black text-white">
        {/* <h1>{"Let's build reddit"}</h1> */}
        <Header />
        <div className="mx-auto mt-6 flex max-w-[70%] gap-4">
          <div className="w-[70%]">
            <PostCreateCard />
          </div>
          <div className="flex-1">
            <BlueitPremium />
          </div>
          {/* <div>
          </div>
          <div>
          </div> */}
        </div>
      </main>
    </>
  );
};

export default Home;
